export const cuisineList = [
  "Phở bò",
  "Phở gà",
  "Bún chả Hà Nội",
  "Nem rán (chả giò)",
  "Gỏi cuốn",
  "Lẩu cá kèo",
  "Lẩu cua đồng",
  "Lẩu hải sản",
  "Cơm tấm sườn bì chả",
  "Gà hấp lá chanh",
  "Vịt quay",
  "Bò lúc lắc",
  "Chả cá Lã Vọng",
  "Cá kho tộ",
  "Mực nhồi thịt",
  "Gà nướng mật ong",
  "Tôm hùm nướng bơ tỏi",
  "Sườn nướng BBQ",
  "Bánh xèo miền Tây",
  "Bánh khọt Vũng Tàu",
  "Mì Quảng",
  "Cao lầu Hội An",
  "Cơm chiên hải sản",
  "Xôi gà xé phay",
  "Chè bưởi",
  "Chè thập cẩm",
];
