export const cuisineList = [
  "Phở bò",
  "Phở gà",
  "Bún chả Hà Nội",
  "Nem rán (chả giò)",
  "Gỏi cuốn",
  "Lẩu cá kèo",
  "Lẩu cua đồng",
  "Lẩu hải sản",
  "Cơm tấm sườn bì chả",
  "Gà hấp lá chanh",
  "Vịt quay",
  "Bò lúc lắc",
  "Chả cá Lã Vọng",
  "Cá kho tộ",
  "Mực nhồi thịt",
  "Gà nướng mật ong",
  "Tôm hùm nướng bơ tỏi",
  "Sườn nướng BBQ",
  "Bánh xèo miền Tây",
  "Bánh khọt Vũng Tàu",
  "Mì Quảng",
  "Cao lầu Hội An",
  "Cơm chiên hải sản",
  "Xôi gà xé phay",
  "Chè bưởi",
  "Chè thập cẩm",
  "Súp hải sản",
  "Súp gà nấm hương",
  "Súp tôm cua",
  "Gỏi ngó sen tôm thịt",
  "Gỏi bò bóp thấu",
  "Gỏi cá mai",
  "Nem nướng Nha Trang",
  "Bánh cuốn Thanh Trì",
  "Cơm gà Hội An",
  "Cơm lam gà nướng",
  "Tôm nướng muối ớt",
  "Tôm xào bơ tỏi",
  "Cá hồi sốt bơ chanh",
  "Cá diêu hồng hấp hành",
  "Mực chiên nước mắm",
  "Sò điệp nướng mỡ hành",
  "Hàu nướng phô mai",
  "Lẩu gà lá giang",
  "Lẩu bò nhúng dấm",
  "Bò nướng lá lốt",
  "Sườn xào chua ngọt",
  "Thịt kho tàu",
  "Gà xào sả ớt",
  "Bánh tráng cuốn thịt heo",
  "Cơm chiên cá mặn",
  "Bún thịt nướng",
  "Bún bò Huế",
  "Hủ tiếu Nam Vang",
  "Miến xào cua",
  "Mì Quảng tôm thịt",
  "Xôi gấc đậu xanh",
  "Bánh flan caramel",
  "Rau câu dừa",
  "Chè khúc bạch",
  "Bánh bông lan trứng muối",
  "Chả giò hải sản",
  "Mực nhúng giấm",
  "Cá mú hấp xì dầu",
  "Bò sốt tiêu đen",
  "Cá kho làng Vũ Đại",
  "Gà nướng đất sét",
  "Vịt nướng mật ong",
  "Lẩu dê nhúng mẻ",
  "Chân giò hầm thuốc bắc",
  "Thịt ba chỉ quay giòn",
  "Cơm hến Huế",
  "Ốc len xào dừa",
  "Ốc móng tay xào tỏi",
  "Gỏi cá trích Phú Quốc",
  "Cơm niêu Sài Gòn",
  "Gà hấp muối sả",
  "Tôm càng xanh hấp bia",
  "Chả mực Hạ Long",
  "Cua rang me",
  "Nghêu hấp sả",
  "Bánh bèo chén",
  "Bánh ít lá gai",
  "Lẩu thập cẩm chua cay",
  "Gà tiềm ớt hiểm",
  "Cá bống kho tiêu",
  "Cơm cháy chà bông",
  "Cháo ếch Singapore",
  "Xôi lá cẩm",
  "Bánh canh cua",
  "Bánh mì xíu mại",
  "Bánh bao nhân xá xíu",
  "Chè đậu xanh đánh",
  "Kem dừa Côn Đảo"
];
